// Code generated by "stringer -output stringer.go -type=internalType"; DO NOT EDIT.

package tpl

import "strconv"

const _internalType_name = "internalInvalidinternalTextinternalLinkinternalQuoteinternalValueinternalIfinternalTryinternalForeachinternalJsinternalFuncinternalFilterinternalVarinternalOperatorinternalSubinternalListinternalSet"

var _internalType_index = [...]uint8{0, 15, 27, 39, 52, 65, 75, 86, 101, 111, 123, 137, 148, 164, 175, 187, 198}

func (i internalType) String() string {
	if i < 0 || i >= internalType(len(_internalType_index)-1) {
		return "internalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _internalType_name[_internalType_index[i]:_internalType_index[i+1]]
}
